# Generated by Django 3.2 on 2021-09-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0002_cause'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cause',
            new_name='causex',
        ),
    ]
