# Generated by Django 3.2 on 2021-09-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='gall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
