# Generated by Django 3.2 on 2021-09-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0006_gall'),
    ]

    operations = [
        migrations.CreateModel(
            name='gall2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='galle2/')),
            ],
        ),
        migrations.AlterField(
            model_name='gall',
            name='image',
            field=models.ImageField(upload_to='galle/'),
        ),
    ]
