# Generated by Django 3.2 on 2021-09-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0007_auto_20210906_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='datex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
