# Generated by Django 3.2 on 2021-09-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0014_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactx',
        ),
    ]
