# Generated by Django 3.2 on 2021-09-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0015_rename_contact_contactx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='td',
            new_name='tdes',
        ),
        migrations.RenameModel(
            old_name='td2',
            new_name='tdes2',
        ),
    ]
