# Generated by Django 3.2 on 2021-09-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0016_auto_20210906_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tdes2',
            new_name='tdata',
        ),
        migrations.RenameModel(
            old_name='tdes',
            new_name='tdata2',
        ),
    ]
