# Generated by Django 3.2 on 2021-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0018_auto_20210906_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='hd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='tdata',
        ),
        migrations.DeleteModel(
            name='tdata2',
        ),
    ]
