# Generated by Django 3.2 on 2021-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0019_auto_20210906_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='hd',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
