# Generated by Django 3.2 on 2021-09-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0020_hd_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hd',
            name='name',
        ),
    ]
