# Generated by Django 3.2 on 2021-09-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0022_hd2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datex',
            new_name='eventss',
        ),
        migrations.RenameModel(
            old_name='gall',
            new_name='gallary',
        ),
        migrations.RenameModel(
            old_name='gall2',
            new_name='gallary2',
        ),
        migrations.RenameModel(
            old_name='hd2',
            new_name='heading1',
        ),
        migrations.RenameModel(
            old_name='hd',
            new_name='heading2',
        ),
    ]
