# Generated by Django 3.2 on 2021-09-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0023_auto_20210907_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteerimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vol/')),
            ],
        ),
    ]
