# Generated by Django 3.2 on 2021-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0025_cover2'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
