# Generated by Django 3.2 on 2021-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0027_auto_20210908_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='volregistercover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='volregcover/')),
            ],
        ),
    ]
