# Generated by Django 3.2 on 2021-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0029_contactxqueryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunterregisterform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='gallary2',
        ),
        migrations.AlterField(
            model_name='contactx',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactxqueryform',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
