# Generated by Django 3.2 on 2021-09-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0030_auto_20210911_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactx',
            new_name='contactxform',
        ),
    ]
