# Generated by Django 3.2 on 2021-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0031_rename_contactx_contactxform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventss',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
